#!/bin/sh

# gen_httpd_conf: generates a simple apache configuration

# url that the user should point to to run this program
# default: http://example.com/~the00z/sentx.net

location="/~the00z/sentx.net"
pwd=`pwd`
postd=`pwd`/../semece.postd

location="${location}/"

# changes multiple trailing / to just one /
location=`echo "$location" | perl -lpe 's!/+$!/!g'`

cat <<END
# I STRONGLY encourage you to put this section inside a 
# <VirtualHost *> </VirtualHost>
# if you don't do it that way, then you deserve what you get

# this is needed to fetch the static/* files
Alias ${location}static $pwd/static
<Location $location >
	AddDefaultCharset	UTF-8
	SetHandler	perl-script
	PerlRequire	$pwd/startup.pl
	PerlHandler	Semece
	# stores top source code dir
	PerlSetVar	SemecePostd	$postd
	Options		+ExecCGI
</Location>
END
